---
categories:
- blog post
format:
  html:
    df-print: paged
    toc: true
text: 
title: கீழே சிக்கன் மண்டி செய்வதற்கான ஒரு ரெசிபி தரப்பட்டுள்ளது. (Recipe to make a delicious Chicken Mandi)

---
சிக்கன் மண்டி ரெசிபி

பொருட்கள்:

1 முழு கோழி, பாதியாக நறுக்கப்பட்டு
2 கப் பாஸ்மதி அரிசி
1 பெரிய வெங்காயம், துண்டுகளாக நறுக்கப்பட்டு
4 பூண்டு பற்கள், நறுக்கப்பட்டு
2 தக்காளி, நறுக்கப்பட்டு
2 டேபிள்ஸ்பூன் எண்ணெய்
1 டீஸ்பூன் சாபரண், 2 டேபிள்ஸ்பூன் சூடான நீரில் ஊறவைக்கப்பட்டு
2 இலவங்கப்பட்டை குச்சிகள்
4 ஏலக்காய் பாக்குகள்
4 கிராம்பு
2 பலா இலைகள்
1 டீஸ்பூன் மஞ்சள் தூள்
1 டீஸ்பூன் சீரகம்
1 டீஸ்பூன் மல்லி தூள்
உப்பு மற்றும் மிளகு, சுவைக்கேற்றபடி
4 கப் நீர்
மண்டி மசாலா தயாரிக்க:

1 டீஸ்பூன் இலவங்கப்பட்டை தூள்
1 டீஸ்பூன் ஏலக்காய் தூள்
1 டீஸ்பூன் கிராம்பு தூள்
1 டீஸ்பூன் மிளகு தூள்
1 டீஸ்பூன் சீரகம் தூள்
தயாரிக்கும் முறை:

சிக்கன் தயார் செய்ய:

ஒரு பெரிய பாத்திரத்தில், எண்ணெயுடன் மஞ்சள் தூள், சீரகம், மல்லி தூள், உப்பு மற்றும் மிளகை சேர்த்து கலக்கவும்.
இந்த கலவையை சிக்கனில் நன்றாக தடவவும், ஒரு மணி நேரத்திற்கு குளிரவையில் வைக்கவும்.
அரிசி தயார் செய்ய:

அரிசியை நன்றாக கழுவி, 30 நிமிடங்கள் குளிர்ந்த நீரில் ஊறவைத்து, பின்னர் வடிகட்டி வைக்கவும்.
பெரிய பாத்திரத்தில், மிதமான சூட்டில் எண்ணெயை சூடாக்கி வெங்காயம் மற்றும் பூண்டை சேர்த்து வதக்கவும்.
தக்காளி மற்றும் மண்டி மசாலா சேர்த்து 5 நிமிடங்கள் வதக்கவும்.
அரிசியை சேர்த்து நன்றாக கலக்கவும், பின்னர் நீரைச் சேர்த்து கொதிக்க விடவும்.
மண்டி தயார் செய்ய:

ஓவன் 180 டிகிரி செல்சியசுக்கு முன்னரிதம் சூடாக்கவும்.
அரிசி மேலே சிக்கனை வைத்துக்கொள்ளவும்.
பாத்திரத்தை அலுமினியம் போர்வையால் மூடி, ஓவனில் ஒரு மணி நேரம் அல்லது சிக்கன் நன்றாக வேகும் வரை வைக்கவும்.
நேரம் முடிந்த பிறகு, அலுமினியப் போர்வையை எடுத்து, சாபரண் நீரை சிக்கனின் மீது பரப்பவும், மேலும் 10 நிமிடங்கள் ஓவனில் வைத்து சிக்கன் பொன்னிறமாகும் வரை வைக்கவும்.
